name: Auto Merge

on:
  pull_request:
    types: [labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ready-to-merge'
    steps:
      - name: Auto-merge PR
        uses: "peter-evans/merge-pull-request@v2"
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash